FROM node:lts-alpine AS base

# # --- Dependencies ---
# FROM base AS deps
# WORKDIR /app
# COPY package.json package-lock.json pnpm-lock.yaml pnpm-workspace.yaml ./
# RUN npm install -g npm@latest
# RUN npm install -g pnpm@latest
# RUN pnpm install --frozen-lockfile
# RUN pnpm build


WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# RUN npm install -g pnpm@latest
# RUN pnpm add prisma@latest

COPY lib ./lib
COPY public ./public
COPY prisma ./prisma
COPY prisma.config.ts ./prisma.config.ts
COPY scripts ./scripts
COPY .next/standalone ./
COPY .next/static ./
COPY node_modules/dotenv ./node_modules/dotenv
COPY node_modules/.prisma ./node_modules/.prisma
COPY node_modules/@prisma ./node_modules/@prisma

# RUN npm install dotenv@latest
# RUN npm install -g npm@latest
# RUN npm install -g pnpm@latest
# RUN pnpm add -D prisma
# RUN pnpm add prisma@latest

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# CMD ["node", "server.js"]
# CMD ["sh", "-c", "node", "/app/server.js"]
# CMD ["sh", "-c", "npx prisma migrate deploy && node server.js"]
CMD ["sh", "-c", "node server.js"]