// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/",
  migrations: {
    path: "prisma/migrations",
    // seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // url: process.env["DATABASE_URL"] || "postgresql://postgres:password@localhost:5432/expense_tracker?schema=public",
  },
});
