# /etc/nginx/conf.d/django.conf

upstream app_servers {
    server 127.0.0.1:8000;
    # server 127.0.0.1:8001;
}

server {
    server_name {{domain_name}};
    listen  80;

    # Redirect to no www.
    set $https_redirect 0;
    if ($server_port = 80) { set $https_redirect 1; }
    if ($host ~ '^www\.') { set $https_redirect 1; }
  
    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Enable this if and only if you use HTTPS
        proxy_set_header X-Forwarded-Proto https;

        # pass the Host: header from the client right along so redirects
        # can be set properly within the Rack application
        proxy_set_header Host $host;

        # we don't want nginx trying to do something clever with
        # redirects, we set the Host: header above already.
        proxy_redirect off;
        proxy_pass http://app_servers;
    }

    location /static {
        autoindex off;
        alias /usr/share/nginx/html/static/;
    }

    location /media {
        autoindex off;
        alias /usr/share/nginx/html/media/;
    }

    location /.well-known {
        alias /usr/share/nginx/html/.well-known/;
    }
}