# GitHub Actions - Repository secrets
# HOST
# PORT
# USERNAME
# FOLDER
# PRIVATE_KEY
# DOCKERHUB_USERNAME
# DOCKERHUB_TOKEN

# Ubuntu: Add "CASignatureAlgorithms +ssh-rsa" to /etc/ssh/sshd_config
# Ubuntu: Add id_rsa.pub to authorized_keys

name: Release to lhchub.com

on:
  push:
    branches: [develop]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v7
      #   with:
      #     fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nextjs:latest

      - name: Remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # 1. Update code from github
            cd /home/${{ secrets.USERNAME }}/${{ secrets.FOLDER }}/ && /usr/bin/git pull

            # 2. Docker restart
            cd /home/${{ secrets.USERNAME }}/${{ secrets.FOLDER }}/ && docker compose down && docker compose pull && docker compose up -d

            # # 0. Environment: pnpm 
            # export NVM_DIR="$HOME/.nvm"
            # [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            # [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

            # 2. Update packages
            # cd /home/${{ secrets.USERNAME }}/${{ secrets.FOLDER }}/ && pnpm install

            # 3. Copy static files to STATIC_ROOT
            # docker update --restart=always nextjs

            # # 5. Clean static cache and compress CSS & JS
            # sudo rm -rf /usr/share/nginx/html/static/CACHE
            # source /home/${{ secrets.USERNAME }}/${{ secrets.FOLDER }}/.venv/bin/activate && cd /home/${{ secrets.USERNAME }}/${{ secrets.FOLDER }} && python ./manage.py compress --force

            # # 6. Update all static files' user & group permission for STATIC_ROOT
            # sudo chown ${{ secrets.USERNAME }}:www-data -R /usr/share/nginx/html/static/

            # # 7. SEO - Ping Google after update with sitemap
            # # source /home/${{ secrets.USERNAME }}/${{ secrets.FOLDER }}/.venv/bin/activate && cd /home/${{ secrets.USERNAME }}/${{ secrets.FOLDER }} && python ./manage.py ping_google

            # # 8. Update Database
            # source /home/${{ secrets.USERNAME }}/${{ secrets.FOLDER }}/.venv/bin/activate && cd /home/${{ secrets.USERNAME }}/${{ secrets.FOLDER }} && python ./manage.py migrate

            # # 9. Restart Django and Nginx
            # sudo systemctl restart daphne
            # # sudo systemctl restart djangoq
